version: '3'
services:
  jenkins:
    image: jenkins_jcasc:1.0.0
    container_name: jenkins
    build:
      context: .
    ports: 
      - 8080:8080
    environment:
      JENKINS_SERVER: ${JENKINS_SERVER}
      JENKINS_ADMIN_ID: ${JENKINS_ADMIN_ID}
      JENKINS_ADMIN_PASSWORD: ${JENKINS_ADMIN_PASSWORD}